### ISSUE TITLE
An example of Emacs+Cider integration

### ISSUE THREAD

**Issue by sskorokhodov** [vouch-opensource/krell#105]
Hi,

Thank you very much for Krell!

I was tinkering with React Native + Krell and spent some time trying to understand how to properly integrate it with Emacs+Cider. I created this issue 1) to ensure that I'm doing right, and 2) if so, to give an extended how-to for those having the same problems.

> Disclaimer: I've never added a custom REPL type to Cider. I'm not an experienced ClojureScript or tools.deps user.

While integrating Krell with Cider I stumbled upon the following problems:

1. As of now, Krell refers to a non-released version of ClojureScript via commit hash. cider/piggieback in its turn refers to a released version via maven version. This leads to tools.deps producing an error trying to resolve the final dependency version.

```text
Error building classpath. Unable to compare versions for org.clojure/clojurescript:
{:mvn/version "1.8.51",
 :deps/manifest :mvn}
and
{:git/url "https://github.com/clojure/clojurescript.git",
 :sha "00079768f9104b17f4130cd710a2f636e046cb07", ...
```

In order to solve that I added `org.clojure/clojurescript` as an explicit dependency to my `deps.edn`.

2. While starting, the REPL prints an exception about missing `react` namespace.

```text
Exception in thread "Thread-15" clojure.lang.ExceptionInfo: null {:clojure.error/source nil, :clojure.error/line nil, :clojure.error/column nil, :clojure.error/phase :compilation}
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:4260)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:4246)
	at cljs.analyzer$analyze_file$fn__5088.invoke(analyzer.cljc:4764)
    ...
Caused by: clojure.lang.ExceptionInfo: No such namespace: react, could not locate react.cljs, react.cljc, or JavaScript source providing "react" in file file:/home/username/.m2/repository/reagent/reagent/0.10.0/reagent-0.10.0.jar!/reagent/core.cljs {:tag :cljs/analysis-error}
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:762)
	at cljs.analyzer$error.invoke(analyzer.cljc:758)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:760)
	at cljs.analyzer$error.invoke(analyzer.cljc:758)
	at cljs.analyzer$analyze_deps.invokeStatic(analyzer.cljc:2636)
	at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:2605)
	at cljs.analyzer$ns_side_effects.invokeStatic(analyzer.cljc:4122)
	at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:4117)
	at cljs.analyzer$analyze_STAR_$fn__4962.invoke(analyzer.cljc:4244)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$reduce.invoke(core.clj:6810)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:4244)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:4235)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:4263)
	... 43 more

```

I solved it by adding the required dependencies into `build.edn`:

```clojure
 :foreign-libs
 [{:file "node_modules/react"
   :provides ["react"]}
  {:file "node_modules/react-dom"
   :provides ["react-dom"]}
  {:file "node_modules/react-native"
   :provides ["react-native"]}]
```

3. Regarding adding a custom CIDER REPL type.

I ended up with `.dir-locals.el` in the project root containing the following:

```lisp
((clojurescript-mode
  (eval . (cider-register-cljs-repl-type
           'krell-cljs
           (concat
            "(do"
            "  (require"
            "    '[clojure.edn :as edn] "
            "    '[cljs.pprint]"
            "    '[clojure.java.io :as io]"
            "    '[cider.piggieback]"
            "    '[krell.api :as krell]"
            "    '[krell.repl])"

            "    (def config (edn/read-string (slurp (io/file \"build.edn\"))))"
            "    (krell/build config)"
            "    (apply cider.piggieback/cljs-repl"
            "      (krell.repl/repl-env)"
            "      (mapcat identity config)))")))
  (cider-default-cljs-repl . krell-cljs)))
```

**Comment by dotemacs** [comment]
See: https://github.com/clojure-emacs/cider/commit/02b5d3f3faa57dbf4eb6fd900cf6b522f1b6dbc5
