### ISSUE TITLE
Reagent tutorial fails when the app starts `Unable to resolve module ./closure_bootstrap.js`

### ISSUE THREAD

**Issue by PEZ** [vouch-opensource/krell#130]
After `clj -M -m krell.main -co build.edn -c -r` I get the message about waitin for device connection at port 5001, as advertised. But when I start the app (iOS) I get this message

```
error: Error: Unable to resolve module ./closure_bootstrap.js from /Users/pez/Projects/tests/AwesomeKrellProject2/target/krell_repl.js: 

None of these files exist:
  * target/closure_bootstrap.js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * target/closure_bootstrap.js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
   6 |     loadFile,
   7 |     onSourceLoad
>  8 | } from "./closure_bootstrap.js";
     |         ^
   9 |
  10 | var CONNECTED = false;
  11 | var RECONNECT_INTERVAL = 3000;
    at ModuleResolver.resolveDependency (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/pez/Projects/tests/AwesomeKrellProject2/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
```

Anyone seen this and know what I can do about it?

**Comment by crowl** [comment]
I'm having the same issue. I believe the cause is in the following line:

https://github.com/vouch-opensource/krell/blob/92115e1f271259e21e67881dd94c2b668e4143d8/src/krell/repl.clj#L244

This line should be moved to the end of the `:post-compile-fn` option of `(cli/default-compile ...)`:

https://github.com/vouch-opensource/krell/blob/92115e1f271259e21e67881dd94c2b668e4143d8/src/krell/repl.clj#L236-L240

**Comment by swannodette** [comment]
Refreshing React Native should make it go away. It hasn't been a show stopper in our projects once `index.js` is written. However it is confusing. Try master - index.js is now always written last.

**Comment by PEZ** [comment]
Yes. Works with `c487f7c3a8ce1b3d74757d5a0af2a776f7704d94`. Thanks!
