### ISSUE TITLE
 When execute command "clj -M -m krell.main -co build.edn -c -r", error encounter

### ISSUE THREAD

**Issue by dataseriesIO** [vouch-opensource/krell#142]
Following the wiki to install krell in an existing AwesomeProject,  when execute the following command in CLI, 
got an error.

MacBookPro:AwesomeProject $ clj -M -m krell.main -co build.edn -c -r
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
clojure.lang.ExceptionInfo: null #:clojure.error{:phase :compilation}
	at cljs.util$compilation_error.invokeStatic(util.cljc:23)
	at cljs.util$compilation_error.invoke(util.cljc:22)
	at cljs.closure$source_for_namespace.invokeStatic(closure.clj:890)
	at cljs.closure$source_for_namespace.invoke(closure.clj:864)
	at cljs.build.api$ns__GT_location.invokeStatic(api.clj:128)
	at cljs.build.api$ns__GT_location.invoke(api.clj:120)
	at cljs.build.api$ns__GT_location.invokeStatic(api.clj:126)
	at cljs.build.api$ns__GT_location.invoke(api.clj:120)
	at cljs.cli$default_compile.invokeStatic(cli.clj:522)
	at cljs.cli$default_compile.invoke(cli.clj:486)
	at krell.repl$krell_compile.invokeStatic(repl.clj:236)
	at krell.repl$krell_compile.invoke(repl.clj:226)
	at cljs.cli$compile_opt.invokeStatic(cli.clj:542)
	at cljs.cli$compile_opt.invoke(cli.clj:540)
	at cljs.cli$main.invokeStatic(cli.clj:703)
	at cljs.cli$main.doInvoke(cli.clj:692)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at cljs.main$_main.invokeStatic(main.clj:65)
	at cljs.main$_main.doInvoke(main.clj:56)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at krell.main$_main.invokeStatic(main.clj:9)
	at krell.main$_main.doInvoke(main.clj:7)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.main$main_opt.invokeStatic(main.clj:514)
	at clojure.main$main_opt.invoke(main.clj:510)
	at clojure.main$main.invokeStatic(main.clj:664)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
Caused by: java.lang.IllegalArgumentException: Namespace awesome-project.core does not exist. Please check that namespaces with dashes use underscores in the ClojureScript file name.
	at cljs.closure$source_for_namespace.invokeStatic(closure.clj:892)
	... 33 more

**Comment by tetriscode** [comment]
Any luck fixing this?

**Comment by jpmonettas** [comment]
Also having this same issue, but after my repl crashes second time I run krell it works.

I also had to run krell with my ip address on linux when using a device, like this `clj -M -m krell.main -h 192.168.1.8 -co build.edn -c -r`

**Comment by bbuccianti** [comment]
Are you sure you're following the guide?

`
Select the "SDK Platforms" tab from within the SDK Manager, then check the box next to "Show Package Details" in the bottom right corner. Look for and expand the Android 10 (Q) entry, then make sure the following items are checked:

Android SDK Platform 29
Intel x86 Atom_64 System Image or Google APIs Intel x86 Atom System Image
`

Check that!

**Comment by fvkluck** [comment]
I'm getting the same error (having followed all instructions carefully). Based on the above comment, I checked the SDK version and noticed that even though I hadn't installed the Android SDK 30, it was in fact installed (Android 11.0 would show 'partially installed'). 
Looking further, I discovered that the Android SDK 30.0 was installed when running `npx react-native run-android`. After some googling I looked at my android/build.gradle file, and there the `buildToolsVersion`, `compileSdkVersion` and `targetSdkVersion` were all set to 30 versions. 
I changed them to 29 versions, and now when running `npx react-native run-android` I'm getting an explanation:
`WARNING:: The specified Android SDK Build Tools version (29.0.2) is ignored, as it is below the minimum supported version (30.0.2) for Android Gradle Plugin 4.2.2.`

According to [this](https://developer.android.com/studio/releases/gradle-plugin#compatibility_3), 4.1.0 is the last Android Gradle Plugin version to support the SDK 29. 4.2.0 was released in March 2021, so to me it seems plausible that this is the cause of this issue.

Disclaimer: this is my first attempt at getting an app to work, and I have no experience with gradle or this ecosystem. I'm not even sure if I 'set' any of the versions in a stable manner :)

I've tried downgrading to 4.1.0 and gradle 6.5, but I haven't succeeded yet. But hopefully the information above helps someone else in analyzing the issue.

**Comment by fvkluck** [comment]
I looked into it a bit more, and my best guess (but I'm in somewhat over my head here) is that this is something about react-native itself that Krel just happens to run into.

The tutorial in https://reactnative.dev/docs/environment-setup#native clearly states that you require Android SDK 29, however, when I run the command listed there `npx react-native init AwesomeProject2` (AwesomeProject was already taken :)), I get the following:
```
android/build.gradle
16:        classpath("com.android.tools.build:gradle:4.2.2")
```
and if I then run `npx react-native start-android`, it will decide to install Android SDK 30 (I assume, but do not have the knowledge to know for certain) because the android gradle plugin 4.2.2 only works with Android SDK 30+)

**Comment by fvkluck** [comment]
Ok, at least on my system it turned out to be a lot easier than expected. When I run `npx react-native init AwesomeProject` (without having Android SDK 30 installed), the AwesomeProject/android/build.grade has the compileSdkVersion and the targetSdkVersion both set to 30. 

A workaround is to edit both to 29, and then for me everything seems to work (starting the app, autoreloading). I'll keep an eye on issues that I encounter that seem related, and I'll try to figure out how/why the versions were set to 30, but for this sunday morning I'm calling it a day :)

**Comment by hadils** [comment]
I'm getting this issue running iOS. I downgraded to 5.2.0 and it went away, but so did the `krell_index.js` support that I am relying on. Here's my details:
```package.json:
{
  "name": "yardwerkz2",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "storybook": "start-storybook -p 7007",
    "build-storybook": "build-storybook"
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|@react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/__mocks__/globalMock.js"
    ]
  },
  "dependencies": {
    "@aws-amplify/codegen-ui": "^2.1.2",
    "@aws-amplify/core": "^4.4.0",
    "@cljs-oss/module-deps": "^1.1.1",
    "@native-base/icons": "^0.0.11",
    "@react-native-async-storage/async-storage": "^1.16.1",
    "@react-native-community/netinfo": "^8.1.0",
    "@react-native-picker/picker": "^2.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "amazon-cognito-identity-js": "^5.2.7",
    "aws-amplify": "^4.3.15",
    "aws-amplify-react-native": "^6.0.3",
    "html-webpack-plugin": "^5.5.0",
    "native-base": "^3.3.7",
    "react": "17.0.2",
    "react-native": "^0.66.4",
    "react-native-action-sheet": "^2.2.0",
    "react-native-device-info": "^8.1.2",
    "react-native-eject": "^0.1.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-safe-area-context": "^4.1.3",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0",
    "react-native-tcp-socket": "^5.2.0",
    "react-native-vector-icons": "^9.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/addon-links": "^5.3",
    "@storybook/addon-ondevice-actions": "^5.3.23",
    "@storybook/addon-ondevice-knobs": "^5.3.25",
    "@storybook/react-native": "^5.3.25",
    "@storybook/react-native-server": "^5.3.23",
    "babel-jest": "^26.6.3",
    "babel-loader": "^8.2.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-dom": "17.0.2",
    "react-test-renderer": "17.0.2"
  }
}

deps.edn:
{:paths     ["src" "test" "js"]
 :deps      {io.vouch/krell                {:mvn/version "0.5.3"}
             ;org.clojure/clojurescript     {:mvn/version "1.11.4"}
             org.clojure/clojure           {:mvn/version "1.10.3"}
             org.clojure/core.async        {:mvn/version "1.5.648"}
             ;com.google.javascript/closure-compiler-unshaded {:mvn/version "v20220202"}
             io.vouch/reagent-react-native {:git/url "https://github.com/vouch-opensource/reagent-react-native.git"
                                            :sha     "0fe1c600c9b81180f76b94ef6004c2f85e7d4aa0"}
             reagent/reagent               {:mvn/version "1.1.1"
                                            :exclusions  [cljsjs/react cljsjs/react-dom]}
             cljsjs/react                  {:mvn/version "18.0.0-rc.0-0"}
             cljsjs/react-dom              {:mvn/version "18.0.0-rc.0-0"}
             cljsjs/react-dom-server       {:mvn/version "18.0.0-rc.0-0"}
             cljsjs/babel-standalone       {:mvn/version "6.18.1-3"}
             com.taoensso/timbre           {:mvn/version "5.1.2"}
             re-frame/re-frame             {:mvn/version "1.3.0-rc3"}

             ;; Datomic
             com.datomic/ion               {:mvn/version "1.0.57"}
             com.datomic/client-cloud      {:mvn/version "1.0.119"}
             com.datomic/dev-local         {:mvn/version "1.0.242"}
             com.google.guava/guava        {:mvn/version "31.1-jre"}

             ;; Logging
             org.slf4j/slf4j-simple        {:mvn/version "1.7.36"}
             }

 :mvn/repos {"datomic-cloud" {:url "s3://datomic-releases-1fc2183a/maven/releases"}}

 :aliases   {:ion-dev   {:main-opts  ["-m" "datomic.ion.dev"]
                         :extra-deps {com.datomic/ion-dev {:mvn/version "1.0.294"}}}
             :clj-tests {:extra-paths ["src/test"]
                         :main-opts   ["-m" "kaocha.runner"]
                         :extra-deps  {lambdaisland/kaocha       {:mvn/version "1.62.993"}
                                       fulcrologic/fulcro-spec   {:mvn/version "3.1.12"}
                                       dev-local-tu/dev-local-tu {:mvn/version "0.2.2"}
                                       orchestra/orchestra       {:mvn/version "0.3.0"}}}}}

Mac OSX 12.5 arm64
```

**Comment by ttchuong** [comment]
In my case, removing node_modules and re-run `npm i` will resolve this issue.

**Comment by mharju** [comment]
This error might be caused due to having wrong `METRO_IP` in `target/closure_bootstrap.js`.
