### ISSUE TITLE
Could not evaluate bundled js code

### ISSUE THREAD

**Issue by CHNB128** [vouch-opensource/krell#155]
I got this error only during running application on iOS. Application stuck waiting for Krell files. 

What should I do or try? Have no idea so far. 

```
Xcode 
15.3

npm --version                                                                                                                                                             10.1.0

node --version                                                                                                                                                            
v20.9.0

java --version                                                                                                                                                            
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

`package.json`
```
{
  "name": "urmobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "krell": "rm -rf target && clj -M -m krell.main -co build.edn -c -r",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@cljs-oss/module-deps": "^1.1.1",
    "@notifee/react-native": "^7.1.0",
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^4.2.1",
    "@react-native-community/push-notification-ios": "^1.8.0",
    "@react-navigation/bottom-tabs": "^6.0.1",
    "@react-navigation/native": "^6.0.1",
    "@react-navigation/native-stack": "^6.0.1",
    "@sentry/react-native": "latest",
    "amplitude-js": "^5.8.0",
    "create-react-class": "15.6.3",
    "deprecated-react-native-prop-types": "^5.0.0",
    "immutable": "^4.0.0-rc.12",
    "react": "18.3.1",
    "react-native": "0.75.4",
    "react-native-actions-sheet": "^0.8.4",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-calendars": "^1.204.0",
    "react-native-charts-wrapper": "^0.5.11",
    "react-native-config": "^1.5.3",
    "react-native-date-picker": "^4.1.3",
    "react-native-device-info": "8.1.2",
    "react-native-dialogs": "^1.0.5",
    "react-native-document-picker": "^8.0.0",
    "react-native-fast-image": "^8.3.4",
    "react-native-file-viewer": "^2.1.5",
    "react-native-geolocation-service": "^5.2.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-html-to-pdf": "^0.12.0",
    "react-native-image-crop-picker": "^0.38.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-interactable": "^2.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-localize": "^1.2.0",
    "react-native-maps": "1.15.0",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-modal": "13.0.1",
    "react-native-permissions": "^3.6.1",
    "react-native-reanimated": "latest",
    "react-native-root-siblings": "^4.1.1",
    "react-native-root-toast": "^3.1.2",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.22.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "12.1.0",
    "react-native-tcp-socket": "5.6.0",
    "react-native-webview": "^11.23.1",
    "react-navigation-backhandler": "^2.0.1",
    "supercluster": "^7.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.75.4",
    "@react-native/eslint-config": "0.75.4",
    "@react-native/metro-config": "0.75.4",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "jetifier": "2.0.0",
    "prettier": "2.8.8"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4",
  "react-native": {
    "xmlhttprequest": false
  },
  "resolutions": {
    "react-native-snap-carousel@^3.9.1": "patch:react-native-snap-carousel@npm%3A3.9.1#./.yarn/patches/react-native-snap-carousel-npm-3.9.1-14bebfe4a7.patch",
    "react-native-calendars@^1.204.0": "patch:react-native-calendars@npm%3A1.1307.0#./.yarn/patches/react-native-calendars-npm-1.1307.0-9526b67117.patch"
  }
}
```

Execution log: 
```
info Reloading connected app(s)...
 BUNDLE  ./index.js

 WARN  socketDidDisconnect with nil clientDelegate for 0
 LOG  Running "urmobile" with {"rootTag":11,"initialProps":{"concurrentRoot":false}}
 LOG  Krell sez howdy, Device ID: iPhone15,4
 LOG  Connected to Krell REPL Server
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/dom/tagname.js [SyntaxError: 9:20:Invalid expression encountered]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/safescript.js [SyntaxError: 14:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/trustedresourceurl.js [SyntaxError: 15:32:Invalid expression encountered]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/safeurl.js [SyntaxError: 14:21:Invalid expression encountered]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/safestyle.js [SyntaxError: 15:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/safestylesheet.js [SyntaxError: 16:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/labs/useragent/highentropy/highentropyvalue.js [SyntaxError: 22:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/labs/useragent/highentropy/highentropydata.js [TypeError: Cannot read property 'HighEntropyValue' of null]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/labs/useragent/browser.js [SyntaxError: 604:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/html/safehtml.js [SyntaxError: 25:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/collections/maps.js [SyntaxError: 9:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/math/long.js [SyntaxError: 11:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/com/cognitect/transit/types.js [TypeError: Cannot read property 'fromString' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/cognitect/transit.js [TypeError: Cannot read property 'prototype' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/async/freelist.js [SyntaxError: 9:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/async/workqueue.js [SyntaxError: 11:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/labs/useragent/platform.js [SyntaxError: 224:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/useragent/useragent.js [TypeError: Cannot read property 'isOpera' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/async/run.js [TypeError: Cannot read property 'prototype' of null]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/promise/resolver.js [SyntaxError: 11:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/promise/promise.js [TypeError: Cannot read property 'prototype' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/log/log.js [SyntaxError: 17:18:Invalid expression encountered]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/net/xhrio.js [TypeError: Cannot read property 'getLogger' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/collections/iters.js [SyntaxError: 20:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/iter/es6.js [SyntaxError: 11:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/structs/heap.js [SyntaxError: 11:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/structs/priorityqueue.js [SyntaxError: 10:1:invalid statement encountered.]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/urbest/common/data_store/utils.js [TypeError: Cannot read property 'call' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/i18n/numberformatsymbolstype.js [SyntaxError: 8:14:Invalid expression encountered]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/goog/useragent/product.js [TypeError: Cannot read property 'isFirefox' of undefined]
 ERROR  Could not evaluate http://192.168.0.21:8081/target/re_graph/logging.js [TypeError: Cannot read property 'getLogger' of undefined]
 WARN  re-frame: overwriting :event handler for: {"_hash": 898695466, "cljs$lang$protocol_mask$partition0$": 2153775105, "cljs$lang$protocol_mask$partition1$": 4096, "fqn": "submit/sync-assignees", "name": "sync-assignees", "ns": "submit"}
Error: ENOENT: no such file or directory, open '/Users/drakenelson/src/urbest/z-frontend/urmobile/JavaScript'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at getCodeFrame (/Users/drakenelson/src/urbest/z-frontend/urmobile/node_modules/metro/src/Server.js:949:18)
    at Server._symbolicate (/Users/drakenelson/src/urbest/z-frontend/urmobile/node_modules/metro/src/Server.js:1026:22)
    at async Server._processRequest (/Users/drakenelson/src/urbest/z-frontend/urmobile/node_modules/metro/src/Server.js:419:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/drakenelson/src/urbest/z-frontend/urmobile/JavaScript'
}
```

**Comment by CHNB128** [comment]
Disabling hermes and new architecture solves problem. 

`Podfile`
```
+ ENV['RCT_NEW_ARCH_ENABLED'] = '0'

...

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
```
