### ISSUE TITLE
Support for :whitespace optimisation

### ISSUE THREAD

**Issue by olivergeorge** [vouch-opensource/krell#69]
Compiling with :simple and :advanced works as expected but :whitespace fails with an error: `:output-wrapper cannot be combined with :optimizations :whitespace`

For example
```
AwesomeProject % clj -m krell.main -w src/cljs -O whitespace -co build.edn -c
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Building ...
java.lang.AssertionError: Assert failed: :output-wrapper cannot be combined with :optimizations :whitespace
(not (and output-wrapper (= :whitespace optimizations)))
        at cljs.closure$check_output_wrapper.invokeStatic(closure.clj:2346)
        at cljs.closure$check_output_wrapper.invoke(closure.clj:2345)
        at cljs.closure$validate_opts.invokeStatic(closure.clj:3016)
        at cljs.closure$validate_opts.invoke(closure.clj:3011)
        at cljs.closure$build.invokeStatic(closure.clj:3059)
        at cljs.closure$build.invoke(closure.clj:3023)
        at cljs.closure$watch$buildf__6288.invoke(closure.clj:3276)
        at cljs.closure$watch.invokeStatic(closure.clj:3308)
        at cljs.closure$watch.invoke(closure.clj:3246)
```

**Comment by swannodette** [comment]
Not going to do this one - haven't felt a need in our own apps for over a year.
